-- stock fundamental
-- income_statement
-- balance_sheet
-- cash_flow

-- Create income_statement table
CREATE TABLE IF NOT EXISTS income_statement(
    ts_code VARCHAR(10) NOT NULL, 
    ann_date DATE NOT NULL,
    f_ann_date DATE NOT NULL,
    end_date DATE NOT NULL,
    report_type VARCHAR(10),
    comp_type VARCHAR(10),
    end_type VARCHAR(10),
    basic_eps FLOAT,   
    diluted_eps FLOAT,   
    total_revenue FLOAT,   
    revenue FLOAT,   
    int_income FLOAT,   
    prem_earned FLOAT,   
    comm_income FLOAT,   
    n_commis_income FLOAT,   
    n_oth_income FLOAT,   
    n_oth_b_income FLOAT,   
    prem_income FLOAT,   
    out_prem FLOAT,   
    une_prem_reser FLOAT,   
    reins_income FLOAT,   
    n_sec_tb_income FLOAT,   
    n_sec_uw_income FLOAT,   
    n_asset_mg_income FLOAT,   
    oth_b_income FLOAT,   
    fv_value_chg_gain FLOAT,   
    invest_income FLOAT,   
    ass_invest_income FLOAT,   
    forex_gain FLOAT,   
    total_cogs FLOAT,   
    oper_cost FLOAT,   
    int_exp FLOAT,   
    comm_exp FLOAT,   
    biz_tax_surchg FLOAT,   
    sell_exp FLOAT,   
    admin_exp FLOAT,   
    fin_exp FLOAT,   
    assets_impair_loss FLOAT,   
    prem_refund FLOAT,   
    compens_payout FLOAT,   
    reser_insur_liab FLOAT,   
    div_payt FLOAT,   
    reins_exp FLOAT,   
    oper_exp FLOAT,   
    compens_payout_refu FLOAT,   
    insur_reser_refu FLOAT,   
    reins_cost_refund FLOAT,   
    other_bus_cost FLOAT,   
    operate_profit FLOAT,   
    non_oper_income FLOAT,   
    non_oper_exp FLOAT,   
    nca_disploss FLOAT,   
    total_profit FLOAT,   
    income_tax FLOAT,   
    n_income FLOAT,   
    n_income_attr_p FLOAT,   
    minority_gain FLOAT,   
    oth_compr_income FLOAT,   
    t_compr_income FLOAT,   
    compr_inc_attr_p FLOAT,   
    compr_inc_attr_m_s FLOAT,   
    ebit FLOAT,   
    ebitda FLOAT,   
    insurance_exp FLOAT,   
    undist_profit FLOAT,   
    distable_profit FLOAT,   
    rd_exp FLOAT,   
    fin_exp_int_exp FLOAT,   
    fin_exp_int_inc FLOAT,   
    transfer_surplus_rese FLOAT,   
    transfer_housing_imprest FLOAT,   
    transfer_oth FLOAT,   
    adj_lossgain FLOAT,   
    withdra_legal_surplus FLOAT,   
    withdra_legal_pubfund FLOAT,   
    withdra_biz_devfund FLOAT,   
    withdra_rese_fund FLOAT,   
    withdra_oth_ersu FLOAT,   
    workers_welfare FLOAT,   
    distr_profit_shrhder FLOAT,   
    prfshare_payable_dvd FLOAT,   
    comshare_payable_dvd FLOAT,   
    capit_comstock_div FLOAT,   
    net_after_nr_lp_correct FLOAT,   
    oth_income FLOAT,   
    asset_disp_income FLOAT,   
    continued_net_profit FLOAT,   
    end_net_profit FLOAT,   
    credit_impa_loss FLOAT,   
    net_expo_hedging_benefits FLOAT,   
    oth_impair_loss_assets FLOAT,   
    total_opcost FLOAT,   
    amodcost_fin_assets FLOAT,   
    update_flag BOOLEAN NOT NULL,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_flag BOOLEAN NOT NULL DEFAULT FALSE,
    PRIMARY KEY(ts_code, f_ann_date, update_flag)
);


-- Create balance_sheet
CREATE TABLE IF NOT EXISTS balance_sheet(
    ts_code VARCHAR(10) NOT NULL,
    ann_date DATE NOT NULL,
    f_ann_date DATE NOT NULL,
    end_date DATE NOT NULL,
    report_type DATE NOT NULL,
    comp_type VARCHAR(10) NOT NULL,
    end_type VARCHAR(10) NOT NULL,
    total_share FLOAT,
    cap_rese FLOAT,
    undistr_porfit FLOAT,
    surplus_rese FLOAT,
    special_rese FLOAT,
    money_cap FLOAT,
    trad_asset FLOAT,
    notes_receiv FLOAT,
    accounts_receiv FLOAT,
    oth_receiv FLOAT,
    prepayment FLOAT,
    div_receiv FLOAT,
    int_receiv FLOAT,
    inventories FLOAT,
    amor_exp FLOAT,
    nca_within_1y FLOAT,
    sett_rsrv FLOAT,
    loanto_oth_bank_fi FLOAT,
    premium_receiv FLOAT,
    reinsur_receiv FLOAT,
    reinsur_res_receiv FLOAT,
    pur_resale_fa FLOAT,
    oth_cur_assets FLOAT,
    total_cur_assets FLOAT,
    fa_avail_for_sale FLOAT,
    htm_invest FLOAT,
    lt_eqt_invest FLOAT,
    invest_real_estate FLOAT,
    time_deposits FLOAT,
    oth_assets FLOAT,
    lt_rec FLOAT,
    fix_assets FLOAT,
    cip FLOAT,
    const_materials FLOAT,
    fixed_assets_disp FLOAT,
    produc_bio_assets FLOAT,
    oil_and_gas_assets FLOAT,
    intan_assets FLOAT,
    r_and_d FLOAT,
    goodwill FLOAT,
    lt_amor_exp FLOAT,
    defer_tax_assets FLOAT,
    decr_in_disbur FLOAT,
    oth_nca FLOAT,
    total_nca FLOAT,
    cash_reser_cb FLOAT,
    depos_in_oth_bfi FLOAT,
    prec_metals FLOAT,
    deriv_assets FLOAT,
    rr_reins_une_prem FLOAT,
    rr_reins_outstd_cla FLOAT,
    rr_reins_lins_liab FLOAT,
    rr_reins_lthins_liab FLOAT,
    refund_depos FLOAT,
    ph_pledge_loans FLOAT,
    refund_cap_depos FLOAT,
    indep_acct_assets FLOAT,
    client_depos FLOAT,
    client_prov FLOAT,
    transac_seat_fee FLOAT,
    invest_as_receiv FLOAT,
    total_assets FLOAT,
    lt_borr FLOAT,
    st_borr FLOAT,
    cb_borr FLOAT,
    depos_ib_deposits FLOAT,
    loan_oth_bank FLOAT,
    trading_fl FLOAT,
    notes_payable FLOAT,
    acct_payable FLOAT,
    adv_receipts FLOAT,
    sold_for_repur_fa FLOAT,
    comm_payable FLOAT,
    payroll_payable FLOAT,
    taxes_payable FLOAT,
    int_payable FLOAT,
    div_payable FLOAT,
    oth_payable FLOAT,
    acc_exp FLOAT,
    deferred_inc FLOAT,
    st_bonds_payable FLOAT,
    payable_to_reinsurer FLOAT,
    rsrv_insur_cont FLOAT,
    acting_trading_sec FLOAT,
    acting_uw_sec FLOAT,
    non_cur_liab_due_1y FLOAT,
    oth_cur_liab FLOAT,
    total_cur_liab FLOAT,
    bond_payable FLOAT,
    lt_payable FLOAT,
    specific_payables FLOAT,
    estimated_liab FLOAT,
    defer_tax_liab FLOAT,
    defer_inc_non_cur_liab FLOAT,
    oth_ncl FLOAT,
    total_ncl FLOAT,
    depos_oth_bfi FLOAT,
    deriv_liab FLOAT,
    depos FLOAT,
    agency_bus_liab FLOAT,
    oth_liab FLOAT,
    prem_receiv_adva FLOAT,
    depos_received FLOAT,
    ph_invest FLOAT,
    reser_une_prem FLOAT,
    reser_outstd_claims FLOAT,
    reser_lins_liab FLOAT,
    reser_lthins_liab FLOAT,
    indept_acc_liab FLOAT,
    pledge_borr FLOAT,
    indem_payable FLOAT,
    policy_div_payable FLOAT,
    total_liab FLOAT,
    treasury_share FLOAT,
    ordin_risk_reser FLOAT,
    forex_differ FLOAT,
    invest_loss_unconf FLOAT,
    minority_int FLOAT,
    total_hldr_eqy_exc_min_int FLOAT,
    total_hldr_eqy_inc_min_int FLOAT,
    total_liab_hldr_eqy FLOAT,
    lt_payroll_payable FLOAT,
    oth_comp_income FLOAT,
    oth_eqt_tools FLOAT,
    oth_eqt_tools_p_shr FLOAT,
    lending_funds FLOAT,
    acc_receivable FLOAT,
    st_fin_payable FLOAT,
    payables FLOAT,
    hfs_assets FLOAT,
    hfs_sales FLOAT,
    cost_fin_assets FLOAT,
    fair_value_fin_assets FLOAT,
    contract_assets FLOAT,
    contract_liab FLOAT,
    accounts_receiv_bill FLOAT,
    accounts_pay FLOAT,
    oth_rcv_total FLOAT,
    fix_assets_total FLOAT,
    cip_total FLOAT,
    oth_pay_total FLOAT,
    long_pay_total FLOAT,
    debt_invest FLOAT,
    oth_debt_invest FLOAT,
    oth_eq_invest FLOAT,
    oth_illiq_fin_assets FLOAT,
    oth_eq_ppbond FLOAT,
    receiv_financing FLOAT,
    use_right_assets FLOAT,
    lease_liab FLOAT,
    update_flag BOOLEAN NOT NULL,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_flag BOOLEAN NOT NULL DEFAULT FALSE,
    PRIMARY KEY(ts_code, f_ann_date, update_flag)
);


-- Create cash_flow
CREATE TABLE IF NOT EXISTS cash_flow(
    ts_code VARCHAR(10) NOT NULL,
    ann_date DATE NOT NULL,
    f_ann_date DATE NOT NULL,
    end_date DATE NOT NULL,
    report_type DATE NOT NULL,
    comp_type VARCHAR(10) NOT NULL,
    end_type VARCHAR(10) NOT NULL,
    net_profit FLOAT,
    finan_exp FLOAT,
    c_fr_sale_sg FLOAT,
    recp_tax_rends FLOAT,
    n_depos_incr_fi FLOAT,
    n_incr_loans_cb FLOAT,
    n_inc_borr_oth_fi FLOAT,
    prem_fr_orig_contr FLOAT,
    n_incr_insured_dep FLOAT,
    n_reinsur_prem FLOAT,
    n_incr_disp_tfa FLOAT,
    ifc_cash_incr FLOAT,
    n_incr_disp_faas FLOAT,
    n_incr_loans_oth_bank FLOAT,
    n_cap_incr_repur FLOAT,
    c_fr_oth_operate_a FLOAT,
    c_inf_fr_operate_a FLOAT,
    c_paid_goods_s FLOAT,
    c_paid_to_for_empl FLOAT,
    c_paid_for_taxes FLOAT,
    n_incr_clt_loan_adv FLOAT,
    n_incr_dep_cbob FLOAT,
    c_pay_claims_orig_inco FLOAT,
    pay_handling_chrg FLOAT,
    pay_comm_insur_plcy FLOAT,
    oth_cash_pay_oper_act FLOAT,
    st_cash_out_act FLOAT,
    n_cashflow_act FLOAT,
    oth_recp_ral_inv_act FLOAT,
    c_disp_withdrwl_invest FLOAT,
    c_recp_return_invest FLOAT,
    n_recp_disp_fiolta FLOAT,
    n_recp_disp_sobu FLOAT,
    stot_inflows_inv_act FLOAT,
    c_pay_acq_const_fiolta FLOAT,
    c_paid_invest FLOAT,
    n_disp_subs_oth_biz FLOAT,
    oth_pay_ral_inv_act FLOAT,
    n_incr_pledge_loan FLOAT,
    stot_out_inv_act FLOAT,
    n_cashflow_inv_act FLOAT,
    c_recp_borrow FLOAT,
    proc_issue_bonds FLOAT,
    oth_cash_recp_ral_fnc_act FLOAT,
    stot_cash_in_fnc_act FLOAT,
    free_cashflow FLOAT,
    c_prepay_amt_borr FLOAT,
    c_pay_dist_dpcp_int_exp FLOAT,
    incl_dvd_profit_paid_sc_ms FLOAT,
    oth_cashpay_ral_fnc_act FLOAT,
    stot_cashout_fnc_act FLOAT,
    n_cash_flows_fnc_act FLOAT,
    eff_fx_flu_cash FLOAT,
    n_incr_cash_cash_equ FLOAT,
    c_cash_equ_beg_period FLOAT,
    c_cash_equ_end_period FLOAT,
    c_recp_cap_contrib FLOAT,
    incl_cash_rec_saims FLOAT,
    uncon_invest_loss FLOAT,
    prov_depr_assets FLOAT,
    depr_fa_coga_dpba FLOAT,
    amort_intang_assets FLOAT,
    lt_amort_deferred_exp FLOAT,
    decr_deferred_exp FLOAT,
    incr_acc_exp FLOAT,
    loss_disp_fiolta FLOAT,
    loss_scr_fa FLOAT,
    loss_fv_chg FLOAT,
    invest_loss FLOAT,
    decr_def_inc_tax_assets FLOAT,
    incr_def_inc_tax_liab FLOAT,
    decr_inventories FLOAT,
    decr_oper_payable FLOAT,
    incr_oper_payable FLOAT,
    others FLOAT,
    im_net_cashflow_oper_act FLOAT,
    conv_debt_into_cap FLOAT,
    conv_copbonds_due_within_1y FLOAT,
    fa_fnc_leases FLOAT,
    im_n_incr_cash_equ FLOAT,
    net_dism_capital_add FLOAT,
    net_cash_rece_sec FLOAT,
    credit_impa_loss FLOAT,
    use_right_asset_dep FLOAT,
    oth_loss_asset FLOAT,
    end_bal_cash FLOAT,
    beg_bal_cash FLOAT,
    end_bal_cash_equ FLOAT,
    beg_bal_cash_equ FLOAT,
    update_flag BOOLEAN NOT NULL,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_flag BOOLEAN NOT NULL DEFAULT FALSE,
    PRIMARY KEY(ts_code, f_ann_date, update_flag)
);
